# -*- coding: utf-8 -*-
"""Inkle.ai Assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RO902YHRDeJSL4QoHhJHloVGYz2MioFA
"""

!pip install requests

import requests

def geocode_place(place_name):
    """Get lat/lon for a place."""
    url = "https://nominatim.openstreetmap.org/search"
    params = {"q": place_name, "format": "json", "limit": 1}
    response = requests.get(url, params=params, headers={"User-Agent": "tourism-agent-colab"})
    data = response.json()
    if not data:
        return None
    return {"lat": float(data[0]["lat"]), "lon": float(data[0]["lon"]), "display_name": data[0]["display_name"]}

def get_weather(lat, lon):
    """Get temperature and rain probability."""
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat,
        "longitude": lon,
        "current_weather": "true",
        "hourly": "precipitation_probability",
        "forecast_days": 1
    }
    r = requests.get(url, params=params)
    data = r.json()
    temp_c = data.get("current_weather", {}).get("temperature")
    rain_probs = data.get("hourly", {}).get("precipitation_probability", [])
    chance_of_rain = max(rain_probs) if rain_probs else None
    return temp_c, chance_of_rain

def get_tourist_places(lat, lon):
    """Get up to 5 POIs from Overpass (tourist attractions)."""
    overpass_url = "https://overpass-api.de/api/interpreter"
    query = f"""
    [out:json][timeout:25];
    (
      node["tourism"="attraction"](around:7500,{lat},{lon});
      node["historic"](around:7500,{lat},{lon});
      node["leisure"](around:7500,{lat},{lon});
      way["tourism"="attraction"](around:7500,{lat},{lon});
      way["historic"](around:7500,{lat},{lon});
      way["leisure"](around:7500,{lat},{lon});
    );
    out center;
    """
    response = requests.post(overpass_url, data=query)
    data = response.json()
    names = []
    for el in data.get("elements", []):
        name = el.get("tags", {}).get("name")
        if name and name not in names:
            names.append(name)
        if len(names) >= 5:
            break
    return names

def plan_trip(place_name, wants_weather=True, wants_places=True):
    """Main orchestration: get info for the place."""
    geo = geocode_place(place_name)
    if not geo:
        return f"I don't know this place: {place_name}"
    resp = f"In {place_name}"
    if wants_weather:
        temp, rain = get_weather(geo["lat"], geo["lon"])
        resp += f" it’s currently {temp}°C"
        if rain is not None:
            resp += f" with a chance of {rain}% to rain."
        else:
            resp += "."
    if wants_places:
        places = get_tourist_places(geo["lat"], geo["lon"])
        if places:
            resp += " And these are the places you can go:\n" + "\n".join(places)
        else:
            resp += " Sorry, I could not find tourist attractions."
    return resp

place = input("Enter the place you want to visit: ").strip()
weather_q = input("Show weather? (yes/no): ").strip().lower()
places_q = input("Show attractions? (yes/no): ").strip().lower()
print()
print(plan_trip(place,
               wants_weather = weather_q in ["yes", "y"],
               wants_places = places_q in ["yes", "y"]))