# -*- coding: utf-8 -*-
"""Inkle Deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCRAGfSg_qOkBM-gxg9D4YjmgqeLRXX1
"""

!pip install gradio

!pip install requests

import sys
sys.path.append('/content/inkle_ai_assessment.py')

import inkle_ai_assessment

import gradio as gr
import inkle_ai_assessment

def run_trip(place, weather, attractions):
    return inkle_ai_assessment.plan_trip(
        place_name=place,
        wants_weather=(weather == "Yes"),
        wants_places=(attractions == "Yes")
    )

with gr.Blocks() as demo:
    gr.Markdown("MULTI-AGENT TOURISM SYSTEM")

    with gr.Row():
        with gr.Column(scale=1):
            place = gr.Textbox(label="Where would you like to visit?")
            weather = gr.Radio(["Yes", "No"], label="Would you like to know the current weather?")
            attractions = gr.Radio(["Yes", "No"], label="Would you like to know the places to visit?")
            btn = gr.Button("Plan Trip")

        with gr.Column(scale=2):
            result = gr.Textbox(
                label="Results",
                lines=12,
                interactive=False
            )

    btn.click(run_trip, [place, weather, attractions], result)

demo.launch()